/**
 * 数据分析类技能定义
 * 场景: data-analyze
 */

import type { SkillDefinition, SkillContext, SkillCategory } from '../core/types';
import { skillRegistry } from '../core/registry';

export const data_analyze_skills: SkillDefinition[] = [
  {
    id: 'analyze-summary',
    name: '基础统计摘要',
    description: '生成数据的基础统计摘要',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['统计', '摘要', '概况'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-summary', message: '技能 基础统计摘要 已执行' } }),
  },
  {
    id: 'analyze-correlation',
    name: '相关性分析',
    description: '计算字段间Pearson相关系数',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['相关', '相关性', '关联'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-correlation', message: '技能 相关性分析 已执行' } }),
  },
  {
    id: 'analyze-trend',
    name: '趋势分析',
    description: '识别数据的时间趋势',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['趋势', '变化', '走势'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-trend', message: '技能 趋势分析 已执行' } }),
  },
  {
    id: 'analyze-distribution',
    name: '分布分析',
    description: '分析数据分布特征',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['分布', '直方', '频率'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-distribution', message: '技能 分布分析 已执行' } }),
  },
  {
    id: 'analyze-groupby',
    name: '分组聚合',
    description: '按维度分组后聚合计算',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['分组', '聚合', '汇总'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-groupby', message: '技能 分组聚合 已执行' } }),
  },
  {
    id: 'analyze-pivot',
    name: '数据透视',
    description: '生成数据透视表',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['透视', '交叉', '汇总'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-pivot', message: '技能 数据透视 已执行' } }),
  },
  {
    id: 'analyze-rank',
    name: '排名分析',
    description: '计算字段值排名',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['排名', '排行', 'top'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-rank', message: '技能 排名分析 已执行' } }),
  },
  {
    id: 'analyze-yoy',
    name: '同比分析',
    description: '计算同比增长率',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['同比', '增长', 'YOY'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-yoy', message: '技能 同比分析 已执行' } }),
  },
  {
    id: 'analyze-mom',
    name: '环比分析',
    description: '计算环比增长率',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['环比', '月度', 'MOM'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-mom', message: '技能 环比分析 已执行' } }),
  },
  {
    id: 'analyze-proportion',
    name: '占比分析',
    description: '计算各部分占总体的比例',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['占比', '比例', '份额'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-proportion', message: '技能 占比分析 已执行' } }),
  },
  {
    id: 'analyze-accumulate',
    name: '累计分析',
    description: '计算累计值和累计占比',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['累计', '累加', '汇总'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-accumulate', message: '技能 累计分析 已执行' } }),
  },
  {
    id: 'analyze-cagr',
    name: '复合增长率',
    description: '计算年均复合增长率CAGR',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['复合', 'CAGR', '增长率'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-cagr', message: '技能 复合增长率 已执行' } }),
  },
  {
    id: 'analyze-variance',
    name: '方差分析',
    description: '计算方差和标准差',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['方差', '标准差', '波动'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-variance', message: '技能 方差分析 已执行' } }),
  },
  {
    id: 'analyze-percentile',
    name: '分位数分析',
    description: '计算四分位数/百分位数',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['分位', '四分位', '中位数'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-percentile', message: '技能 分位数分析 已执行' } }),
  },
  {
    id: 'analyze-frequency',
    name: '频次分析',
    description: '统计值出现频次',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['频次', '计数', '出现'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-frequency', message: '技能 频次分析 已执行' } }),
  },
  {
    id: 'analyze-anomaly',
    name: '异常检测',
    description: '自动检测数据中的异常点',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['异常', '检测', '离群'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-anomaly', message: '技能 异常检测 已执行' } }),
  },
  {
    id: 'analyze-forecast',
    name: '简单预测',
    description: '基于历史数据的简单线性预测',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['预测', '预估', '趋势'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-forecast', message: '技能 简单预测 已执行' } }),
  },
  {
    id: 'analyze-insight',
    name: '智能洞察',
    description: '自动生成数据洞察建议',
    category: 'data-analyze' as SkillCategory,
    sceneBindings: ['data-analyze'],
    parameters: [],
    dependencies: [],
    keywords: ['洞察', '发现', '建议'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'analyze-insight', message: '技能 智能洞察 已执行' } }),
  },
];

/** 注册所有数据分析技能 */
export function registerSkills(): void {
  skillRegistry.registerMany(data_analyze_skills);
}