/**
 * 数据清洗类技能定义
 * 场景: data-clean
 */

import type { SkillDefinition, SkillContext, SkillCategory } from '../core/types';
import { skillRegistry } from '../core/registry';

export const data_clean_skills: SkillDefinition[] = [
  {
    id: 'clean-dedup',
    name: '重复值删除',
    description: '识别并删除重复行/列',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['去重', '重复', '重复值'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-dedup', message: '技能 重复值删除 已执行' } }),
  },
  {
    id: 'clean-fill-null',
    name: '缺失值填充',
    description: '用均值/中位数/前值填充空值',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['填充', '空值', '缺失'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-fill-null', message: '技能 缺失值填充 已执行' } }),
  },
  {
    id: 'clean-trim-space',
    name: '空格清理',
    description: '去除单元格首尾多余空格',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['空格', '清理', 'trim'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-trim-space', message: '技能 空格清理 已执行' } }),
  },
  {
    id: 'clean-standardize-case',
    name: '大小写统一',
    description: '统一文本大小写格式',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['大小写', '统一', '标准'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-standardize-case', message: '技能 大小写统一 已执行' } }),
  },
  {
    id: 'clean-format-date',
    name: '日期格式统一',
    description: '将多种日期格式统一为标准格式',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['日期', '格式', '统一'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-format-date', message: '技能 日期格式统一 已执行' } }),
  },
  {
    id: 'clean-format-number',
    name: '数值格式统一',
    description: '统一数值精度和小数位数',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['数值', '精度', '小数'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-format-number', message: '技能 数值格式统一 已执行' } }),
  },
  {
    id: 'clean-remove-symbols',
    name: '特殊符号清理',
    description: '去除文本中的特殊符号和乱码',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['符号', '乱码', '清理'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-remove-symbols', message: '技能 特殊符号清理 已执行' } }),
  },
  {
    id: 'clean-outlier-iqr',
    name: '异常值检测(IQR)',
    description: '使用IQR方法检测异常值',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['异常', '离群', 'IQR'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-outlier-iqr', message: '技能 异常值检测(IQR) 已执行' } }),
  },
  {
    id: 'clean-outlier-zscore',
    name: '异常值检测(Z-Score)',
    description: '使用Z-Score方法检测异常值',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['Z分数', '标准差', '异常'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-outlier-zscore', message: '技能 异常值检测(Z-Score) 已执行' } }),
  },
  {
    id: 'clean-split-column',
    name: '列拆分',
    description: '按分隔符拆分单列数据',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['拆分', '分列', '分割'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-split-column', message: '技能 列拆分 已执行' } }),
  },
  {
    id: 'clean-merge-columns',
    name: '列合并',
    description: '将多列合并为一列',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['合并', '拼接', '列合并'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-merge-columns', message: '技能 列合并 已执行' } }),
  },
  {
    id: 'clean-transpose',
    name: '行列转置',
    description: '交换行和列的位置',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['转置', '行列', '交换'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-transpose', message: '技能 行列转置 已执行' } }),
  },
  {
    id: 'clean-filter-rows',
    name: '条件行过滤',
    description: '按条件筛选保留行',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['过滤', '筛选', '条件'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-filter-rows', message: '技能 条件行过滤 已执行' } }),
  },
  {
    id: 'clean-sort',
    name: '数据排序',
    description: '按单列/多列排序',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['排序', '排列', '顺序'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-sort', message: '技能 数据排序 已执行' } }),
  },
  {
    id: 'clean-replace',
    name: '批量替换',
    description: '批量替换单元格内容',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['替换', '查找', '修改'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-replace', message: '技能 批量替换 已执行' } }),
  },
  {
    id: 'clean-type-convert',
    name: '数据类型转换',
    description: '文本/数值/日期类型互转',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['类型', '转换', '格式'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-type-convert', message: '技能 数据类型转换 已执行' } }),
  },
  {
    id: 'clean-normalize',
    name: '数据归一化',
    description: '将数值归一化到0-1范围',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['归一化', '标准化', '缩放'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-normalize', message: '技能 数据归一化 已执行' } }),
  },
  {
    id: 'clean-strip-html',
    name: 'HTML标签清理',
    description: '去除文本中的HTML标签',
    category: 'data-clean' as SkillCategory,
    sceneBindings: ['data-clean'],
    parameters: [],
    dependencies: [],
    keywords: ['HTML', '标签', '网页'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'clean-strip-html', message: '技能 HTML标签清理 已执行' } }),
  },
];

/** 注册所有数据清洗技能 */
export function registerSkills(): void {
  skillRegistry.registerMany(data_clean_skills);
}