/**
 * 公式计算类技能定义
 * 场景: formula
 */

import type { SkillDefinition, SkillContext, SkillCategory } from '../core/types';
import { skillRegistry } from '../core/registry';

export const formula_skills: SkillDefinition[] = [
  {
    id: 'formula-sum',
    name: '求和公式',
    description: '生成SUM求和公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['求和', '合计', 'sum'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-sum', message: '技能 求和公式 已执行' } }),
  },
  {
    id: 'formula-average',
    name: '平均值公式',
    description: '生成AVERAGE平均值公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['平均', '均值', 'average'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-average', message: '技能 平均值公式 已执行' } }),
  },
  {
    id: 'formula-count',
    name: '计数公式',
    description: '生成COUNT计数公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['计数', '统计', 'count'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-count', message: '技能 计数公式 已执行' } }),
  },
  {
    id: 'formula-countif',
    name: '条件计数公式',
    description: '生成COUNTIF条件计数公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['条件计数', 'countif'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-countif', message: '技能 条件计数公式 已执行' } }),
  },
  {
    id: 'formula-sumif',
    name: '条件求和公式',
    description: '生成SUMIF条件求和公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['条件求和', 'sumif'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-sumif', message: '技能 条件求和公式 已执行' } }),
  },
  {
    id: 'formula-vlookup',
    name: '查找公式',
    description: '生成VLOOKUP/LOOKUP查找公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['查找', '匹配', 'vlookup'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-vlookup', message: '技能 查找公式 已执行' } }),
  },
  {
    id: 'formula-if',
    name: '条件公式',
    description: '生成IF条件判断公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['条件', '判断', 'if'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-if', message: '技能 条件公式 已执行' } }),
  },
  {
    id: 'formula-maxmin',
    name: '最值公式',
    description: '生成MAX/MIN最大值最小值公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['最大', '最小', 'max', 'min'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-maxmin', message: '技能 最值公式 已执行' } }),
  },
  {
    id: 'formula-round',
    name: '四舍五入公式',
    description: '生成ROUND取整公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['四舍五入', '取整', 'round'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-round', message: '技能 四舍五入公式 已执行' } }),
  },
  {
    id: 'formula-text',
    name: '文本处理公式',
    description: '生成文本拼接/截取/替换公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['文本', '拼接', '截取'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-text', message: '技能 文本处理公式 已执行' } }),
  },
  {
    id: 'formula-date',
    name: '日期计算公式',
    description: '生成日期差/工作日计算公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['日期', '天数', '工作日'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-date', message: '技能 日期计算公式 已执行' } }),
  },
  {
    id: 'formula-percentage',
    name: '百分比公式',
    description: '生成占比/百分比计算公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['百分比', '占比', 'percent'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-percentage', message: '技能 百分比公式 已执行' } }),
  },
  {
    id: 'formula-growth',
    name: '增长率公式',
    description: '生成环比/同比增长率公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['增长率', '增速', '同比'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-growth', message: '技能 增长率公式 已执行' } }),
  },
  {
    id: 'formula-rank',
    name: '排名公式',
    description: '生成RANK排名公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['排名', 'rank', '名次'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-rank', message: '技能 排名公式 已执行' } }),
  },
  {
    id: 'formula-nested',
    name: '嵌套复杂公式',
    description: '生成多层嵌套复杂公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['嵌套', '复杂', '多层'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-nested', message: '技能 嵌套复杂公式 已执行' } }),
  },
  {
    id: 'formula-array',
    name: '数组公式',
    description: '生成数组/动态数组公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['数组', '动态', 'array'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-array', message: '技能 数组公式 已执行' } }),
  },
  {
    id: 'formula-cross-ref',
    name: '跨表引用公式',
    description: '生成跨工作表引用公式',
    category: 'formula' as SkillCategory,
    sceneBindings: ['formula'],
    parameters: [],
    dependencies: [],
    keywords: ['跨表', '引用', '跨工作表'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'formula-cross-ref', message: '技能 跨表引用公式 已执行' } }),
  },
];

/** 注册所有公式计算技能 */
export function registerSkills(): void {
  skillRegistry.registerMany(formula_skills);
}