/**
 * 表格生成类技能定义
 * 场景: table-generate
 */

import type { SkillDefinition, SkillContext, SkillCategory } from '../core/types';
import { skillRegistry } from '../core/registry';

export const table_generate_skills: SkillDefinition[] = [
  {
    id: 'gen-blank-table',
    name: '空白表格生成',
    description: '生成指定行列数的空白表格',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['空白', '新建', '创建表格'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-blank-table', message: '技能 空白表格生成 已执行' } }),
  },
  {
    id: 'gen-from-template',
    name: '模板表格生成',
    description: '基于预制模板快速生成表格',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['模板', '套用', '从模板'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-from-template', message: '技能 模板表格生成 已执行' } }),
  },
  {
    id: 'gen-from-text',
    name: '文本转表格',
    description: '将自然语言描述转为结构化表格',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['文本转表', '描述', '文字'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-from-text', message: '技能 文本转表格 已执行' } }),
  },
  {
    id: 'gen-monthly-sales',
    name: '月度销售表生成',
    description: '生成月度销售跟踪表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['月销', '销售表', '月度'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-monthly-sales', message: '技能 月度销售表生成 已执行' } }),
  },
  {
    id: 'gen-inventory',
    name: '库存管理表生成',
    description: '生成库存出入库管理表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['库存', '入库', '出库'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-inventory', message: '技能 库存管理表生成 已执行' } }),
  },
  {
    id: 'gen-project-track',
    name: '项目跟踪表生成',
    description: '生成项目进度跟踪表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['项目', '进度', '跟踪'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-project-track', message: '技能 项目跟踪表生成 已执行' } }),
  },
  {
    id: 'gen-expense',
    name: '费用报销表生成',
    description: '生成费用报销台账',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['报销', '费用', '台账'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-expense', message: '技能 费用报销表生成 已执行' } }),
  },
  {
    id: 'gen-asset',
    name: '固定资产表生成',
    description: '生成固定资产登记管理表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['固定资产', '资产', '折旧'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-asset', message: '技能 固定资产表生成 已执行' } }),
  },
  {
    id: 'gen-ledger',
    name: '收支台账生成',
    description: '生成通用收支台账',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['收支', '台账', '账本'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-ledger', message: '技能 收支台账生成 已执行' } }),
  },
  {
    id: 'gen-attendance',
    name: '考勤表生成',
    description: '生成员工考勤统计表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['考勤', '打卡', '出勤'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-attendance', message: '技能 考勤表生成 已执行' } }),
  },
  {
    id: 'gen-payroll',
    name: '工资表生成',
    description: '生成员工工资计算表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['工资', '薪酬', '薪资'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-payroll', message: '技能 工资表生成 已执行' } }),
  },
  {
    id: 'gen-crm',
    name: '客户管理表生成',
    description: '生成客户信息跟踪表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['客户', 'CRM', '跟进'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-crm', message: '技能 客户管理表生成 已执行' } }),
  },
  {
    id: 'gen-purchase',
    name: '采购订单表生成',
    description: '生成采购订单管理表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['采购', '订单', '进货'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-purchase', message: '技能 采购订单表生成 已执行' } }),
  },
  {
    id: 'gen-schedule',
    name: '排班表生成',
    description: '生成员工排班计划表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['排班', '班次', '轮班'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-schedule', message: '技能 排班表生成 已执行' } }),
  },
  {
    id: 'gen-kpi',
    name: 'KPI考核表生成',
    description: '生成绩效考核评分表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['KPI', '绩效', '考核'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-kpi', message: '技能 KPI考核表生成 已执行' } }),
  },
  {
    id: 'gen-survey',
    name: '调查问卷表生成',
    description: '生成调查问卷数据表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['问卷', '调查', '收集'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-survey', message: '技能 调查问卷表生成 已执行' } }),
  },
  {
    id: 'gen-budget',
    name: '预算表生成',
    description: '生成年度/月度预算表',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['预算', '计划', '预估'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-budget', message: '技能 预算表生成 已执行' } }),
  },
  {
    id: 'gen-contract',
    name: '合同台账生成',
    description: '生成合同管理台账',
    category: 'table-generate' as SkillCategory,
    sceneBindings: ['table-generate'],
    parameters: [],
    dependencies: [],
    keywords: ['合同', '协议', '签约'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'gen-contract', message: '技能 合同台账生成 已执行' } }),
  },
];

/** 注册所有表格生成技能 */
export function registerSkills(): void {
  skillRegistry.registerMany(table_generate_skills);
}