/**
 * 文档解析类技能定义
 * 场景: document-parse
 */

import type { SkillDefinition, SkillContext, SkillCategory } from '../core/types';
import { skillRegistry } from '../core/registry';

export const document_parse_skills: SkillDefinition[] = [
  {
    id: 'parse-excel',
    name: 'Excel文件解析',
    description: '解析Excel文件为结构化数据',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['excel', 'xlsx', '导入'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-excel', message: '技能 Excel文件解析 已执行' } }),
  },
  {
    id: 'parse-csv',
    name: 'CSV文件解析',
    description: '解析CSV文件为结构化数据',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['csv', '逗号', '导入'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-csv', message: '技能 CSV文件解析 已执行' } }),
  },
  {
    id: 'parse-pdf-table',
    name: 'PDF表格提取',
    description: '从PDF中提取表格数据',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['pdf', '提取', '表格'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-pdf-table', message: '技能 PDF表格提取 已执行' } }),
  },
  {
    id: 'parse-word-table',
    name: 'Word表格提取',
    description: '从Word文档中提取表格',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['word', 'docx', '文档'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-word-table', message: '技能 Word表格提取 已执行' } }),
  },
  {
    id: 'parse-text-table',
    name: '文本表格识别',
    description: '从纯文本中识别表格结构',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['文本', '识别', '结构'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-text-table', message: '技能 文本表格识别 已执行' } }),
  },
  {
    id: 'parse-image-ocr',
    name: '图片OCR识别',
    description: '识别图片中的表格文字',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['图片', 'OCR', '识别'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-image-ocr', message: '技能 图片OCR识别 已执行' } }),
  },
  {
    id: 'parse-html-table',
    name: 'HTML表格提取',
    description: '从网页HTML中提取表格',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['html', '网页', '抓取'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-html-table', message: '技能 HTML表格提取 已执行' } }),
  },
  {
    id: 'parse-json',
    name: 'JSON数据解析',
    description: '解析JSON数组为表格',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['json', 'api', '接口'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-json', message: '技能 JSON数据解析 已执行' } }),
  },
  {
    id: 'parse-api',
    name: 'API数据接入',
    description: '调用API获取数据转为表格',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['api', '接口', '数据'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-api', message: '技能 API数据接入 已执行' } }),
  },
  {
    id: 'parse-database',
    name: '数据库查询接入',
    description: '连接数据库查询数据',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['数据库', 'sql', '查询'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-database', message: '技能 数据库查询接入 已执行' } }),
  },
  {
    id: 'parse-clipboard',
    name: '剪贴板数据解析',
    description: '从剪贴板粘贴数据解析',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['剪贴板', '粘贴', '复制'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-clipboard', message: '技能 剪贴板数据解析 已执行' } }),
  },
  {
    id: 'parse-markdown',
    name: 'Markdown表格解析',
    description: '解析Markdown表格语法',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['markdown', 'md', '表格'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-markdown', message: '技能 Markdown表格解析 已执行' } }),
  },
  {
    id: 'parse-xml',
    name: 'XML数据解析',
    description: '解析XML数据为表格',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['xml', '标签', '解析'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-xml', message: '技能 XML数据解析 已执行' } }),
  },
  {
    id: 'parse-log',
    name: '日志文件解析',
    description: '解析结构化日志数据',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['日志', 'log', '文件'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-log', message: '技能 日志文件解析 已执行' } }),
  },
  {
    id: 'parse-merge-files',
    name: '多文件合并解析',
    description: '合并多个文件数据为一个表格',
    category: 'document-parse' as SkillCategory,
    sceneBindings: ['document-parse'],
    parameters: [],
    dependencies: [],
    keywords: ['合并', '多文件', '汇总'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'parse-merge-files', message: '技能 多文件合并解析 已执行' } }),
  },
];

/** 注册所有文档解析技能 */
export function registerSkills(): void {
  skillRegistry.registerMany(document_parse_skills);
}