/**
 * 可视化类技能定义
 * 场景: visualize
 */

import type { SkillDefinition, SkillContext, SkillCategory } from '../core/types';
import { skillRegistry } from '../core/registry';

export const visualize_skills: SkillDefinition[] = [
  {
    id: 'viz-bar',
    name: '柱状图生成',
    description: '生成柱状图展示分类数据',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['柱状', '条形', 'bar'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-bar', message: '技能 柱状图生成 已执行' } }),
  },
  {
    id: 'viz-line',
    name: '折线图生成',
    description: '生成折线图展示趋势数据',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['折线', '趋势', 'line'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-line', message: '技能 折线图生成 已执行' } }),
  },
  {
    id: 'viz-pie',
    name: '饼图生成',
    description: '生成饼图展示占比数据',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['饼图', '占比', 'pie'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-pie', message: '技能 饼图生成 已执行' } }),
  },
  {
    id: 'viz-scatter',
    name: '散点图生成',
    description: '生成散点图展示相关性',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['散点', '分布', 'scatter'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-scatter', message: '技能 散点图生成 已执行' } }),
  },
  {
    id: 'viz-area',
    name: '面积图生成',
    description: '生成面积图展示累积趋势',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['面积', '累积', 'area'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-area', message: '技能 面积图生成 已执行' } }),
  },
  {
    id: 'viz-radar',
    name: '雷达图生成',
    description: '生成雷达图展示多维对比',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['雷达', '多维', 'radar'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-radar', message: '技能 雷达图生成 已执行' } }),
  },
  {
    id: 'viz-heatmap',
    name: '热力图生成',
    description: '生成热力图展示密度/强度',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['热力', '密度', 'heatmap'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-heatmap', message: '技能 热力图生成 已执行' } }),
  },
  {
    id: 'viz-funnel',
    name: '漏斗图生成',
    description: '生成漏斗图展示转化流程',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['漏斗', '转化', 'funnel'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-funnel', message: '技能 漏斗图生成 已执行' } }),
  },
  {
    id: 'viz-sankey',
    name: '桑基图生成',
    description: '生成桑基图展示流向关系',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['桑基', '流向', 'sankey'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-sankey', message: '技能 桑基图生成 已执行' } }),
  },
  {
    id: 'viz-waterfall',
    name: '瀑布图生成',
    description: '生成瀑布图展示增减变化',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['瀑布', '增减', 'waterfall'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-waterfall', message: '技能 瀑布图生成 已执行' } }),
  },
  {
    id: 'viz-gauge',
    name: '仪表盘生成',
    description: '生成仪表盘展示KPI完成度',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['仪表', 'KPI', 'gauge'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-gauge', message: '技能 仪表盘生成 已执行' } }),
  },
  {
    id: 'viz-wordcloud',
    name: '词云生成',
    description: '生成词云展示文本频次',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['词云', '文字', 'wordcloud'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-wordcloud', message: '技能 词云生成 已执行' } }),
  },
  {
    id: 'viz-treemap',
    name: '树图生成',
    description: '生成树图展示层级占比',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['树图', '层级', 'treemap'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-treemap', message: '技能 树图生成 已执行' } }),
  },
  {
    id: 'viz-boxplot',
    name: '箱线图生成',
    description: '生成箱线图展示分布特征',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['箱线', '分位', 'boxplot'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-boxplot', message: '技能 箱线图生成 已执行' } }),
  },
  {
    id: 'viz-combo',
    name: '组合图生成',
    description: '生成柱状+折线组合图',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['组合', '混合', 'combo'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-combo', message: '技能 组合图生成 已执行' } }),
  },
  {
    id: 'viz-dashboard',
    name: '仪表盘布局',
    description: '自动组合多个图表为仪表盘',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['仪表盘', '面板', 'dashboard'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-dashboard', message: '技能 仪表盘布局 已执行' } }),
  },
  {
    id: 'viz-table',
    name: '表格可视化',
    description: '生成条件格式化的数据表格',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['表格', '条件格式', 'table'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-table', message: '技能 表格可视化 已执行' } }),
  },
  {
    id: 'viz-map',
    name: '地图可视化',
    description: '生成地图展示地理分布',
    category: 'visualize' as SkillCategory,
    sceneBindings: ['visualize'],
    parameters: [],
    dependencies: [],
    keywords: ['地图', '地理', 'map'],
    strategy: 'hybrid',
    maxRetries: 2,
    timeout: 30000,
    handler: async (_params: Record<string, unknown>, _ctx: SkillContext) => ({ success: true, data: { skillId: 'viz-map', message: '技能 地图可视化 已执行' } }),
  },
];

/** 注册所有可视化技能 */
export function registerSkills(): void {
  skillRegistry.registerMany(visualize_skills);
}