/**
 * 教育科研领域工作流定义
 */

import type { WorkflowDefinition, WorkflowCategory } from '../core/types';
import { workflowRegistry } from '../core/registry';

export const education_workflows: WorkflowDefinition[] = [
  {
    id: 'wf-student-grade',
    name: '学生成绩分析',
    description: '导入成绩→班级统计→排名→成绩分布→挂科预警',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'analyze-rank', condition: null },
      { skillId: 'viz-histogram', condition: null },
      { skillId: 'viz-boxplot', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-course-evaluation',
    name: '课程评价分析',
    description: '导入评价→维度统计→趋势对比→改进建议',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'analyze-trend', condition: null },
      { skillId: 'viz-radar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-research-data',
    name: '实验数据处理',
    description: '导入实验数据→清洗→统计分析→图表生成→报告',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'clean-outlier-zscore', condition: null },
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'viz-scatter', condition: null },
      { skillId: 'viz-line', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-survey-research',
    name: '调研问卷分析',
    description: '导入问卷→描述统计→交叉分析→信效度→报告',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-frequency', condition: null },
      { skillId: 'analyze-correlation', condition: null },
      { skillId: 'viz-bar', condition: null },
      { skillId: 'viz-heatmap', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-literature-review',
    name: '文献综述整理',
    description: '导入文献→分类统计→关键词提取→趋势分析',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-frequency', condition: null },
      { skillId: 'viz-wordcloud', condition: null },
      { skillId: 'viz-treemap', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-class-attendance',
    name: '课堂出勤分析',
    description: '导入考勤→出勤率→迟到早退→预警→学期汇总',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'analyze-trend', condition: null },
      { skillId: 'viz-line', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-enrollment-trend',
    name: '招生趋势分析',
    description: '导入招生→历年对比→专业分布→预测',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-yoy', condition: null },
      { skillId: 'analyze-forecast', condition: null },
      { skillId: 'viz-line', condition: null },
      { skillId: 'viz-pie', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-thesis-format',
    name: '论文格式检查',
    description: '导入论文→格式校验→引用检查→排版规范',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'clean-standardize-case', condition: null },
      { skillId: 'clean-strip-html', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-competition-score',
    name: '竞赛评分汇总',
    description: '导入评分→去掉最高最低→平均分→排名',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'analyze-rank', condition: null },
      { skillId: 'viz-bar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-funding-track',
    name: '科研经费跟踪',
    description: '导入经费→预算执行→报销进度→结余预警',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-yoy', condition: null },
      { skillId: 'viz-gauge', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-publication-stat',
    name: '论文发表统计',
    description: '导入论文→期刊分类→影响因子→趋势分析',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'analyze-trend', condition: null },
      { skillId: 'viz-bar', condition: null },
      { skillId: 'viz-line', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-teaching-evaluation',
    name: '教学评估汇总',
    description: '导入评估→指标统计→排名→反馈整理',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'analyze-rank', condition: null },
      { skillId: 'viz-radar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-internship-track',
    name: '实习跟踪',
    description: '导入实习→企业统计→岗位分布→满意度',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'analyze-proportion', condition: null },
      { skillId: 'viz-pie', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-graduation-track',
    name: '毕业跟踪',
    description: '导入毕业→就业率→去向统计→薪资分析',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-proportion', condition: null },
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'viz-pie', condition: null },
      { skillId: 'viz-bar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-library-borrow',
    name: '图书借阅分析',
    description: '导入借阅→热门图书→借阅趋势→读者画像',
    category: 'education' as WorkflowCategory,
    sceneBindings: ['education'],
    tags: ['education', '自动化'],
    steps: [
      { skillId: 'analyze-frequency', condition: null },
      { skillId: 'analyze-trend', condition: null },
      { skillId: 'viz-wordcloud', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
];

/** 注册所有教育科研工作流 */
export function registerWorkflows(): void {
  workflowRegistry.registerMany(education_workflows);
}