/**
 * 财务人事领域工作流定义
 */

import type { WorkflowDefinition, WorkflowCategory } from '../core/types';
import { workflowRegistry } from '../core/registry';

export const finance_workflows: WorkflowDefinition[] = [
  {
    id: 'wf-payroll-calc',
    name: '工资计算',
    description: '导入考勤→计算基本工资→五险一金→个税→实发工资',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'gen-payroll', condition: null },
      { skillId: 'formula-sum', condition: null },
      { skillId: 'formula-if', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-expense-reimburse',
    name: '费用报销汇总',
    description: '导入报销单→分类汇总→审批流程→付款清单',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'gen-expense', condition: null },
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-pie', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-cash-flow',
    name: '现金流量分析',
    description: '导入收支→分类汇总→流入流出→净现金流',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'gen-ledger', condition: null },
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-waterfall', condition: null },
      { skillId: 'viz-line', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-profit-analysis',
    name: '利润分析',
    description: '导入收入成本→计算毛利→费用扣除→净利润',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'formula-sum', condition: null },
      { skillId: 'formula-percentage', condition: null },
      { skillId: 'viz-bar', condition: null },
      { skillId: 'viz-pie', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-budget-control',
    name: '预算控制',
    description: '导入预算→实际对比→偏差分析→预警提醒',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'gen-budget', condition: null },
      { skillId: 'analyze-yoy', condition: null },
      { skillId: 'viz-gauge', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-tax-calc',
    name: '税务计算',
    description: '导入收入→税率匹配→税额计算→申报表生成',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'formula-if', condition: null },
      { skillId: 'formula-percentage', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-ar-ap-aging',
    name: '应收应付账龄',
    description: '导入应收应付→账龄分段→逾期标记→催款清单',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'formula-date', condition: null },
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-cost-allocation',
    name: '成本分摊',
    description: '导入成本→分摊规则→按比例分摊→分摊结果',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'analyze-proportion', condition: null },
      { skillId: 'formula-percentage', condition: null },
      { skillId: 'viz-pie', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-kpi-scorecard',
    name: '绩效考核评分',
    description: '导入KPI→权重计算→打分→排名→结果汇总',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'gen-kpi', condition: null },
      { skillId: 'analyze-rank', condition: null },
      { skillId: 'viz-radar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-headcount-plan',
    name: '人力编制规划',
    description: '导入编制→实际对比→缺口分析→招聘建议',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'analyze-yoy', condition: null },
      { skillId: 'viz-table', condition: null },
      { skillId: 'viz-bar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-training-track',
    name: '培训跟踪',
    description: '导入培训→出勤统计→考核结果→培训效果',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-recruitment-pipeline',
    name: '招聘Pipeline',
    description: '导入候选人→阶段统计→转化率→周期分析',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-funnel', condition: null },
      { skillId: 'formula-date', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-benefit-analysis',
    name: '福利成本分析',
    description: '导入福利→分类统计→人均成本→趋势分析',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'analyze-mom', condition: null },
      { skillId: 'viz-pie', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-turnover-analysis',
    name: '离职率分析',
    description: '导入离职→部门统计→原因分类→趋势预警',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'analyze-proportion', condition: null },
      { skillId: 'viz-line', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-salary-benchmark',
    name: '薪酬对标',
    description: '导入薪酬→岗位匹配→市场对标→竞争力分析',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-scatter', condition: null },
      { skillId: 'viz-radar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-financial-report',
    name: '财务报表生成',
    description: '导入科目余额→资产负债表→利润表→现金流量表',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'formula-sum', condition: null },
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-depreciation-calc',
    name: '折旧计算',
    description: '导入固定资产→选择折旧方法→计算折旧→生成折旧表',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'gen-asset', condition: null },
      { skillId: 'formula-sum', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-reimburse-audit',
    name: '报销审计',
    description: '导入报销→规则校验→异常标记→审计报告',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'clean-outlier-iqr', condition: null },
      { skillId: 'analyze-anomaly', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-bank-reconcile',
    name: '银行对账',
    description: '导入银行流水→系统数据→自动匹配→差异标记',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'clean-dedup', condition: null },
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-invoice-match',
    name: '发票匹配',
    description: '导入发票→订单匹配→金额校验→匹配结果',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'clean-dedup', condition: null },
      { skillId: 'formula-sumif', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-project-cost',
    name: '项目成本核算',
    description: '导入项目收支→成本归集→利润计算→项目报告',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'formula-sum', condition: null },
      { skillId: 'viz-bar', condition: null },
      { skillId: 'viz-pie', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-year-end-close',
    name: '年终决算',
    description: '导入全年数据→科目汇总→损益结转→决算报告',
    category: 'finance' as WorkflowCategory,
    sceneBindings: ['finance'],
    tags: ['finance', '自动化'],
    steps: [
      { skillId: 'formula-sum', condition: null },
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
];

/** 注册所有财务人事工作流 */
export function registerWorkflows(): void {
  workflowRegistry.registerMany(finance_workflows);
}