/**
 * 通用办公领域工作流定义
 */

import type { WorkflowDefinition, WorkflowCategory } from '../core/types';
import { workflowRegistry } from '../core/registry';

export const general_workflows: WorkflowDefinition[] = [
  {
    id: 'wf-data-upload-clean',
    name: '数据上传与清洗',
    description: '上传文件→解析→自动清洗→去重→格式统一',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'parse-excel', condition: null },
      { skillId: 'clean-dedup', condition: null },
      { skillId: 'clean-fill-null', condition: null },
      { skillId: 'clean-trim-space', condition: null },
      { skillId: 'clean-format-date', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-table-create-basic',
    name: '快速建表',
    description: '选择模板→生成表格→添加示例数据→设置格式',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'gen-from-template', condition: null },
      { skillId: 'clean-type-convert', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-table-create-advanced',
    name: '高级建表',
    description: '需求描述→AI生成表头→生成示例→公式计算→格式美化',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'gen-from-text', condition: null },
      { skillId: 'formula-sum', condition: null },
      { skillId: 'formula-average', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-data-summary-report',
    name: '数据摘要报告',
    description: '选择数据→统计摘要→生成洞察→导出报告',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'analyze-insight', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-monthly-report',
    name: '月度数据报告',
    description: '汇总月度数据→同比环比→趋势图→导出PDF',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'analyze-yoy', condition: null },
      { skillId: 'analyze-mom', condition: null },
      { skillId: 'viz-line', condition: null },
      { skillId: 'viz-bar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-kpi-dashboard',
    name: 'KPI仪表盘',
    description: '选择KPI指标→计算完成度→生成仪表盘→设置预警',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'viz-gauge', condition: null },
      { skillId: 'viz-dashboard', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-data-export-package',
    name: '数据导出打包',
    description: '选择数据→多格式导出→压缩打包→分享链接',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'parse-excel', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-multi-file-merge',
    name: '多文件合并',
    description: '选择多个文件→字段映射→合并去重→输出汇总表',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'parse-merge-files', condition: null },
      { skillId: 'clean-dedup', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-auto-format',
    name: '表格自动美化',
    description: '读取表格→智能识别类型→应用格式→条件高亮→生成图表',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'clean-type-convert', condition: null },
      { skillId: 'viz-table', condition: null },
      { skillId: 'viz-bar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-attendance-summary',
    name: '考勤汇总统计',
    description: '导入考勤→计算出勤率→异常标记→生成月度汇总',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'gen-attendance', condition: null },
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-expense-approval',
    name: '费用报销审批',
    description: '导入报销单→分类统计→审批状态跟踪→汇总导出',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'gen-expense', condition: null },
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-pie', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-contact-merge',
    name: '联系人合并去重',
    description: '导入联系人→姓名匹配→去重合并→输出干净列表',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'clean-dedup', condition: null },
      { skillId: 'clean-merge-columns', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-schedule-generate',
    name: '智能排班生成',
    description: '输入人员→设置规则→生成排班表→冲突检测',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'gen-schedule', condition: null },
      { skillId: 'analyze-summary', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-inventory-check',
    name: '库存盘点',
    description: '导入库存→自动对账→差异标记→生成盘点报告',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'gen-inventory', condition: null },
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-contract-track',
    name: '合同到期跟踪',
    description: '导入合同→计算到期日→预警提醒→状态跟踪',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'gen-contract', condition: null },
      { skillId: 'formula-date', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-budget-vs-actual',
    name: '预算执行对比',
    description: '导入预算和实际→对比分析→差异计算→生成对比表',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'gen-budget', condition: null },
      { skillId: 'analyze-yoy', condition: null },
      { skillId: 'viz-waterfall', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-data-quality-check',
    name: '数据质量检查',
    description: '扫描全表→完整性检查→一致性校验→生成质检报告',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'clean-fill-null', condition: null },
      { skillId: 'clean-outlier-iqr', condition: null },
      { skillId: 'analyze-summary', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-survey-analysis',
    name: '问卷结果分析',
    description: '导入问卷→选项统计→交叉分析→生成报告',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'gen-survey', condition: null },
      { skillId: 'analyze-frequency', condition: null },
      { skillId: 'viz-pie', condition: null },
      { skillId: 'viz-bar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-meeting-minutes',
    name: '会议纪要转表格',
    description: '导入纪要→提取任务→分配人员→设置截止日期',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'parse-text-table', condition: null },
      { skillId: 'clean-split-column', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-asset-management',
    name: '固定资产管理',
    description: '导入资产→计算折旧→状态跟踪→生成资产台账',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'gen-asset', condition: null },
      { skillId: 'formula-sum', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-email-list-clean',
    name: '邮件列表清洗',
    description: '导入邮件→格式校验→去重→分类标记',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'clean-dedup', condition: null },
      { skillId: 'clean-trim-space', condition: null },
      { skillId: 'clean-type-convert', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-address-standardize',
    name: '地址标准化',
    description: '导入地址→解析省市区→标准化格式→校验邮编',
    category: 'general' as WorkflowCategory,
    sceneBindings: ['general'],
    tags: ['general', '自动化'],
    steps: [
      { skillId: 'clean-standardize-case', condition: null },
      { skillId: 'clean-split-column', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
];

/** 注册所有通用办公工作流 */
export function registerWorkflows(): void {
  workflowRegistry.registerMany(general_workflows);
}