/**
 * 项目运营领域工作流定义
 */

import type { WorkflowDefinition, WorkflowCategory } from '../core/types';
import { workflowRegistry } from '../core/registry';

export const project_workflows: WorkflowDefinition[] = [
  {
    id: 'wf-project-plan',
    name: '项目计划制定',
    description: '输入项目→分解WBS→排期→资源分配→甘特图',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'gen-project-track', condition: null },
      { skillId: 'formula-date', condition: null },
      { skillId: 'viz-gantt', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-project-progress',
    name: '项目进度跟踪',
    description: '导入进度→完成度计算→偏差分析→预警',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'viz-gantt', condition: null },
      { skillId: 'viz-gauge', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-risk-register',
    name: '风险登记册',
    description: '导入风险→概率评估→影响分析→风险矩阵',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-heatmap', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-resource-allocation',
    name: '资源分配优化',
    description: '导入资源→负载计算→冲突检测→优化建议',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-heatmap', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-milestone-track',
    name: '里程碑跟踪',
    description: '导入里程碑→状态跟踪→延期分析→燃尽图',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'formula-date', condition: null },
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'viz-line', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-issue-track',
    name: '问题跟踪',
    description: '导入问题→分类统计→优先级→解决时效',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-pie', condition: null },
      { skillId: 'viz-bar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-change-control',
    name: '变更控制',
    description: '导入变更请求→影响评估→审批状态→实施跟踪',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-funnel', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-stakeholder-matrix',
    name: '干系人分析',
    description: '导入干系人→影响力评估→沟通策略→矩阵图',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-scatter', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-quality-metric',
    name: '质量度量',
    description: '导入质量数据→缺陷统计→测试覆盖率→趋势',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'analyze-trend', condition: null },
      { skillId: 'viz-line', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-earned-value',
    name: '挣值分析',
    description: '导入PV/EV/AC→计算SPI/CPI→偏差分析→趋势',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'formula-sum', condition: null },
      { skillId: 'analyze-yoy', condition: null },
      { skillId: 'viz-line', condition: null },
      { skillId: 'viz-gauge', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-lessons-learned',
    name: '经验教训库',
    description: '导入教训→分类归档→搜索→知识沉淀',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-frequency', condition: null },
      { skillId: 'viz-wordcloud', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-meeting-track',
    name: '会议跟踪',
    description: '导入会议→议题统计→决议跟踪→行动项',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'formula-date', condition: null },
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-doc-version',
    name: '文档版本管理',
    description: '导入文档→版本统计→变更对比→审批状态',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-treemap', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-team-velocity',
    name: '团队速率分析',
    description: '导入迭代数据→速率计算→容量规划→预测',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-trend', condition: null },
      { skillId: 'analyze-forecast', condition: null },
      { skillId: 'viz-line', condition: null },
      { skillId: 'viz-bar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-sprint-review',
    name: '迭代评审',
    description: '导入迭代→完成度→缺陷→回顾→改进项',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'viz-radar', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-release-plan',
    name: '发布计划',
    description: '导入需求→优先级→依赖分析→发布排期',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'formula-date', condition: null },
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-gantt', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-incident-track',
    name: '事故跟踪',
    description: '导入事故→分类统计→MTTR→根因分析',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'formula-date', condition: null },
      { skillId: 'viz-bar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-sla-monitor',
    name: 'SLA监控',
    description: '导入SLA→达标率→违规统计→趋势预警',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'analyze-trend', condition: null },
      { skillId: 'viz-gauge', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-cost-baseline',
    name: '成本基线',
    description: '导入预算→实际→基线对比→偏差预警',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-yoy', condition: null },
      { skillId: 'viz-waterfall', condition: null },
      { skillId: 'viz-line', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-demand-forecast',
    name: '需求预测',
    description: '导入历史需求→趋势→季节性→容量规划',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-trend', condition: null },
      { skillId: 'analyze-forecast', condition: null },
      { skillId: 'viz-line', condition: null },
      { skillId: 'viz-area', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-knowledge-base',
    name: '知识库构建',
    description: '导入文档→分类→标签→搜索索引→知识图谱',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'analyze-frequency', condition: null },
      { skillId: 'viz-wordcloud', condition: null },
      { skillId: 'viz-treemap', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-onboard-track',
    name: '入职跟踪',
    description: '导入入职→任务清单→完成度→导师分配',
    category: 'project' as WorkflowCategory,
    sceneBindings: ['project'],
    tags: ['project', '自动化'],
    steps: [
      { skillId: 'formula-date', condition: null },
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'viz-gantt', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
];

/** 注册所有项目运营工作流 */
export function registerWorkflows(): void {
  workflowRegistry.registerMany(project_workflows);
}