/**
 * 销售零售领域工作流定义
 */

import type { WorkflowDefinition, WorkflowCategory } from '../core/types';
import { workflowRegistry } from '../core/registry';

export const sales_workflows: WorkflowDefinition[] = [
  {
    id: 'wf-sales-daily',
    name: '日销售报表',
    description: '导入销售→按品类汇总→计算环比→生成日报',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'gen-monthly-sales', condition: null },
      { skillId: 'analyze-mom', condition: null },
      { skillId: 'viz-bar', condition: null },
      { skillId: 'viz-line', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-sales-funnel',
    name: '销售漏斗分析',
    description: '导入线索→阶段统计→转化率计算→生成漏斗图',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-funnel', condition: null },
      { skillId: 'viz-sankey', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-product-ranking',
    name: '商品销售排行',
    description: '导入销售→按SKU汇总→排序→生成Top10排行',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-rank', condition: null },
      { skillId: 'viz-bar', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-region-sales',
    name: '区域销售分析',
    description: '导入销售→按区域分组→地图可视化→对比分析',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-map', condition: null },
      { skillId: 'viz-heatmap', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-customer-segment',
    name: '客户分群分析',
    description: '导入客户→RFM分析→分群标记→分组统计',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-scatter', condition: null },
      { skillId: 'viz-pie', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-promotion-effect',
    name: '促销效果分析',
    description: '导入促销前后数据→对比分析→增量计算→效果评估',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-yoy', condition: null },
      { skillId: 'analyze-mom', condition: null },
      { skillId: 'viz-waterfall', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-inventory-warning',
    name: '库存预警',
    description: '导入库存→安全库存比对→预警生成→补货建议',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'gen-inventory', condition: null },
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'viz-gauge', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-sales-forecast',
    name: '销售预测',
    description: '导入历史销售→趋势分析→季节性调整→生成预测',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-trend', condition: null },
      { skillId: 'analyze-forecast', condition: null },
      { skillId: 'viz-line', condition: null },
      { skillId: 'viz-area', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-crm-pipeline',
    name: 'CRM商机Pipeline',
    description: '导入商机→阶段统计→赢率计算→Pipeline生成',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'gen-crm', condition: null },
      { skillId: 'analyze-proportion', condition: null },
      { skillId: 'viz-funnel', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-retail-analytics',
    name: '零售门店分析',
    description: '导入门店数据→坪效计算→人效分析→排名对比',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-rank', condition: null },
      { skillId: 'viz-radar', condition: null },
      { skillId: 'viz-heatmap', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-commission-calc',
    name: '销售提成计算',
    description: '导入销售→按规则计算提成→汇总→生成工资单',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'formula-sumif', condition: null },
      { skillId: 'formula-percentage', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-return-analysis',
    name: '退货分析',
    description: '导入退货→原因分类→占比分析→趋势跟踪',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'analyze-proportion', condition: null },
      { skillId: 'viz-pie', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-price-analysis',
    name: '价格带分析',
    description: '导入商品→价格分段→销量统计→最优价格区间',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-distribution', condition: null },
      { skillId: 'viz-histogram', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-competitor-track',
    name: '竞品跟踪',
    description: '导入竞品数据→价格对比→功能对比→SWOT表',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-radar', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-channel-analysis',
    name: '渠道销售分析',
    description: '导入渠道数据→分渠道统计→ROI计算→渠道排名',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'analyze-rank', condition: null },
      { skillId: 'viz-bar', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-seasonal-analysis',
    name: '季节性销售分析',
    description: '导入多年数据→季节性分解→同比分析→预测',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-trend', condition: null },
      { skillId: 'analyze-yoy', condition: null },
      { skillId: 'viz-line', condition: null },
      { skillId: 'viz-area', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-new-product-launch',
    name: '新品上市跟踪',
    description: '导入新品数据→周销跟踪→对比老品→上市效果评估',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-mom', condition: null },
      { skillId: 'viz-line', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-loyalty-analysis',
    name: '会员忠诚度分析',
    description: '导入会员数据→复购率→活跃度→流失预警',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-frequency', condition: null },
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'viz-gauge', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-abc-analysis',
    name: 'ABC分类管理',
    description: '导入SKU→销售额排序→ABC分类→差异化策略',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-rank', condition: null },
      { skillId: 'analyze-proportion', condition: null },
      { skillId: 'viz-pie', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-wholesale-track',
    name: '批发订单跟踪',
    description: '导入批发订单→发货状态→回款跟踪→异常提醒',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'gen-purchase', condition: null },
      { skillId: 'formula-date', condition: null },
      { skillId: 'viz-table', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-gift-card-analysis',
    name: '礼品卡分析',
    description: '导入礼品卡→余额统计→使用率→过期预警',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'analyze-summary', condition: null },
      { skillId: 'formula-date', condition: null },
      { skillId: 'viz-gauge', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wf-omni-channel',
    name: '全渠道数据汇总',
    description: '导入线上线下→统一口径→汇总分析→全渠道视图',
    category: 'sales' as WorkflowCategory,
    sceneBindings: ['sales'],
    tags: ['sales', '自动化'],
    steps: [
      { skillId: 'parse-merge-files', condition: null },
      { skillId: 'analyze-groupby', condition: null },
      { skillId: 'viz-dashboard', condition: null },
    ],
    errorStrategy: 'fallback',
    maxRetries: 2,
    timeout: 120000,
    isBuiltin: true,
    isTemplate: true,
    createdAt: new Date().toISOString(),
  },
];

/** 注册所有销售零售工作流 */
export function registerWorkflows(): void {
  workflowRegistry.registerMany(sales_workflows);
}